version: 0.1.{build}
image:
- Visual Studio 2017
# - Ubuntu1804
configuration: Release
platform: Any CPU
install:
- pwsh: scripts/install.ps1
build_script:
- pwsh: scripts/build.ps1
after_build:
- pwsh: scripts/publish.ps1
test_script:
- pwsh: scripts/test.ps1
artifacts:
- path: '\'
  name: MyMessenger_All_Files
- path: 'MyMessenger.Server.Console\bin\Release\netcoreapp2.2\publish\'
  name: MyMessenger_Server_$(APPVEYOR_BUILD_VERSION)
- path: 'MyMessenger.Client.Console\bin\Release\netcoreapp2.2\publish\'
  name: MyMessenger_Client_$(APPVEYOR_BUILD_VERSION)
- path: '\MyMessenger.Client.Console\publish\MyMessenger_Client_$(APPVEYOR_REPO_TAG_NAME)_linux-x64'
  name: MyMessenger_Client_$(APPVEYOR_REPO_TAG_NAME)_linux-x64
- path: '\MyMessenger.Client.Console\publish\MyMessenger_Client_$(APPVEYOR_REPO_TAG_NAME)_win-x64'
  name: MyMessenger_Client_$(APPVEYOR_REPO_TAG_NAME)_win-x64
- path: '\MyMessenger.Client.Console\publish\MyMessenger_Client_$(APPVEYOR_REPO_TAG_NAME)_win-x86'
  name: MyMessenger_Client_$(APPVEYOR_REPO_TAG_NAME)_win-x86
- path: '\MyMessenger.Server.Console\publish\MyMessenger_Server_$(APPVEYOR_REPO_TAG_NAME)_linux-x64'
  name: MyMessenger_Server_$(APPVEYOR_REPO_TAG_NAME)_linux-x64
- path: '\MyMessenger.Server.Console\publish\MyMessenger_Server_$(APPVEYOR_REPO_TAG_NAME)_win-x64'
  name: MyMessenger_Server_$(APPVEYOR_REPO_TAG_NAME)_win-x64
- path: '\MyMessenger.Server.Console\publish\MyMessenger_Server_$(APPVEYOR_REPO_TAG_NAME)_win-x86'
  name: MyMessenger_Server_$(APPVEYOR_REPO_TAG_NAME)_win-x86
deploy:
- provider: FTP
  host: 
    secure: tgFBLOzwRuRs8x/0Mq7WEw==
  protocol: sftp
  username: vladislav
  password:
    secure: Ms8unA4ChOoYMeatsRrA/g==
  folder: MyMessenger\MyMessenger-$(APPVEYOR_BUILD_VERSION)
  application: MyMessenger-$(APPVEYOR_BUILD_VERSION)
  on:
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017 
    SHOULD_DEPLOY: true
- provider: GitHub
  tag: $(appveyor_repo_tag_name)
  release: MyMessenger $(appveyor_repo_tag_name)
  description: $(appveyor_repo_tag_name) $(APPVEYOR_BUILD_VERSION)
  auth_token:
    secure: Npd8Pdh2luH0INNPoAQXoPC2g71ZM39Ys1Cu842ZZaRFt6B45Or6vy1bV10x0oSn
  artifact: MyMessenger_All_Files; MyMessenger_Client_$(APPVEYOR_BUILD_VERSION); MyMessenger_Client_$(APPVEYOR_REPO_TAG_NAME)_linux-x64; MyMessenger_Client_$(APPVEYOR_REPO_TAG_NAME)_win-x64; MyMessenger_Client_$(APPVEYOR_REPO_TAG_NAME)_win-x86; MyMessenger_Server_$(APPVEYOR_REPO_TAG_NAME)_linux-x64; MyMessenger_Server_$(APPVEYOR_REPO_TAG_NAME)_win-x64; MyMessenger_Server_$(APPVEYOR_REPO_TAG_NAME)_win-x86
  draft: false
  prerelease: true
  on:
    branch: develop
    appveyor_repo_tag: true